version: '3.8'

services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    hostname: kafka
    container_name: kafka
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    ports:
      - "9092:9092"

  storm-nimbus:
    hostname: storm-nimbus
    container_name: storm-nimbus
    image: storm:2.6.2
    command: storm nimbus
    depends_on:
      - zookeeper
    environment:
      - STORM_ZOOKEEPER_SERVERS=["zookeeper"]
    ports:
      - "6627:6627"

  storm-supervisor:
    hostname: storm-supervisor
    container_name: storm-supervisor
    image: storm:2.6.2
    command: storm supervisor
    depends_on:
      - storm-nimbus
      - zookeeper
    environment:
      - STORM_ZOOKEEPER_SERVERS=["zookeeper"]

  storm-ui:
    hostname: storm-ui
    container_name: storm-ui
    image: storm:2.6.2
    command: storm ui
    depends_on:
      - storm-nimbus
    ports:
      - "8080:8080"

  kafka-ui:
    hostname: kafka-ui
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

